/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsExamIdRouteImport } from './routes/results.$examId'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsExamIdRoute = ResultsExamIdRouteImport.update({
  id: '/results/$examId',
  path: '/results/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/results/$examId': typeof ResultsExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/results/$examId': typeof ResultsExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/results/$examId': typeof ResultsExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam/$examId' | '/results/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$examId' | '/results/$examId'
  id: '__root__' | '/' | '/exam/$examId' | '/results/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  ResultsExamIdRoute: typeof ResultsExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$examId': {
      id: '/results/$examId'
      path: '/results/$examId'
      fullPath: '/results/$examId'
      preLoaderRoute: typeof ResultsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  ResultsExamIdRoute: ResultsExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
